title: KjvRam
description:  Here, you can find cool stuff I work on.
remote_theme: tuur29/pages-themes-cayman
darkmode: true
color:
  header: "#000"
  gradient_left: "#6a0dad"
  gradient_right: "#FF0000"
logo_url: 
gems:
- jekyll-seo-tag
