title: KjvRam
description:  Here, you can find cool stuff I work on.
remote_theme: tuur29/pages-themes-cayman
darkmode: true
color:
  header: "#000"
  gradient_left: "#f9cb85"
  gradient_right: "#e99c57"
logo_url: https://kjvram.github.io/assets/img/ramwithcross.png
gems:
- jekyll-seo-tag
