title: Romans Road
description:  Here, you can find cool stuff I work on.
remote_theme: tuur29/pages-themes-cayman
darkmode: false
color:
  header: "#000"
  gradient_left: "#ffffff"
  gradient_right: "#ffffff"
logo_url: 
gems:
- jekyll-seo-tag
